spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinelog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: cinelog
    password: cinelog
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  hikari:
    pool-name: cinelog-pool
    minimum-idle: 2
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    transaction-isolation: TRANSACTION_READ_COMMITTED

  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml


springdoc:
  api-docs:
    path: /v3/api-docs        # JSON da especificação
  swagger-ui:
    path: /swagger-ui         # UI acessível em /swagger-ui (redireciona p/ index)
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{traceId:-na}:%X{spanId:-na}] %logger{36} - %msg%n"

