services:
  otel-collector:
    image: otel/opentelemetry-collector:0.106.0
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.6.0
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - 3200:3200

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:11.3.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - tempo

volumes:
  tempo-data:
